package me.newgen.team.permission;

public enum TeamPermission {
    INVITE_MEMBER,
    KICK_MEMBER,
    MANAGE_ROLES,
    REVIEW_INVITES,
    REVIEW_JOIN_REQUESTS,
    RENAME_TEAM,
    EDIT_SETTINGS,
    DISBAND_TEAM,
    TRANSFER_LEADER,

    CHEST_OPEN,
    CHEST_DEPOSIT,
    CHEST_WITHDRAW,
    CHEST_UPGRADE,

    SET_HOME,
    TELEPORT_HOME,
    DELETE_HOME,

    MANAGE_RELATIONS,
    TOGGLE_TEAM_CHAT,
    MANAGE_MEMBERS,
    WITHDRAW_BALANCE
}
